###
GET http://localhost:3000/users

###
GET http://localhost:3000/products

###
GET http://localhost:3000/users/:41f1421a-57d5-44db-b610-040cb373557b

###
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "이클립스",
  "price": 3000,
  "stock": 30,
  "category": "BEAUTY"
}

###
POST http://localhost:3000/users
Content-Type: application/json

{
  "email": "coowew@fake.com",
  "firstName": "비파향",
  "lastName": "ddd",
  "address": "sdsd"
}

###
PATCH http://localhost:3000/users/:4e5e6fb7-834a-4dc1-8303-ee98b3596ed3
Content-Content-Type: application/json

{
  "name": "partial@eclipse.com"
}